depends:
    - test-runner
    - crc
    - cmp

source:
    - checksum_block.c
    - serialization.c

tests:
    - tests/block_checksum_tests.cpp
    - tests/serializer_tests.cpp
    - tests/messagepack_tests.cpp
    - tests/integration_tests.cpp

